title: ElvUI.NET
baseurl: "/elvui.net"
url: "https://chaoticweg.cc/elvui.net"

show_downloads: true

repository: chaoticweg/elvui.net

# Build settings
markdown: kramdown
theme: minima
plugins:
  - "jekyll-github-metadata"
